ubuntu_release: "bionic"

go_version: "1.13"
go_install_dir: "/opt/go-{{ go_version }}"
go_path: "~/dev/go"
go_dep_version: "0.5.0"

# Module version to use for the offifical gopls tool (e.g. "HEAD", a branch
# name, a tag name, or a commit hash).
gopls_version: "9cc4af7"
# Repo version to checkout for saibing's gopls fork (e.g. "HEAD", a branch
# name, a tag name, or a commit hash).
gopls_saibing_version: "9c5d92334b9cfef9cb18277154186aa9c6bd1bb4"

protoc_version: "3.7.1"
protoc_install_dir: "/opt/protoc-{{ protoc_version }}"

nodejs_repo_version: "node_8.x"

ccls_version: "0.20190301"

python_language_server_version: "2019.1"

# terraform
tf_version: "0.12.7"
tf_install_dir: "/opt/tf-{{ tf_version }}"

kubectl_version: "1.16.2"
helm_version: "2.13.1"
helm_install_dir: "/opt/helm-{{ helm_version }}"
# kind: kubernetes-in-docker
kind_version: "0.5.1"
clusterawsadm_version: "0.4.2"
