ubuntu_release: "focal"

# emacs version (tag or commit) to build from source.
# for example, "emacs-27.1" or "86d8d76aa3"
emacs_rev: "emacs-27.1"

#
# Go
#
go_version: "1.14.6"
go_install_dir: "/opt/go-{{ go_version }}"
go_path: "~/dev/go"
delve_version: "1.5.0"
go_dep_version: "0.5.0"
# Module version to use for the offifical gopls tool (e.g. "HEAD", a branch
# name, a tag name, or a commit hash).
gopls_version: "v0.5.0-pre1"
golangci_lint_version: "v1.27.0"
protoc_version: "3.7.1"
protoc_install_dir: "/opt/protoc-{{ protoc_version }}"

nodejs_repo_version: "node_12.x"

#
# C/C++
#
clangd_version: "10.0.0"
ccls_version: "0.20190823.5"

#
# Python
#
dotnet_sdk_version: "3.1"
# python language server
pyright_ls_version: "1.1.65"
# alternative python language server
python_language_server_version: "0.2"
pyenv_version: "v1.2.20"
# python versions to install in pyenv
pyenv_py_versions: ["2.7.18", "3.8.5"]
# interpreters to set as default, globally
pyenv_global_versions: "3.8.5 2.7.18"
pyenv_virtualenv_version: "v1.1.5"

#
# Ruby
#
# lsp server
solargraph_version: "0.39.15"

#
# Terraform
#
tf_version: "0.12.19"
tf_install_dir: "/opt/tf-{{ tf_version }}"
# language server version
tf_ls_version: "v0.0.11-beta2"


# Packer
packer_version: "1.5.1"

eclipse_version: "2019-12"
eclipse_install_dir: "/opt/eclipse-{{ eclipse_version }}"

#
# Kubernetes
#
kubectl_version: "1.16.3"
helm_version: "2.16.1"
helm_install_dir: "/opt/helm-{{ helm_version }}"
helm_secrets_version: "v2.0.2"
minikube_version: "1.5.2"
# kind: kubernetes-in-docker
kind_version: "0.7.0"
clusterawsadm_version: "0.4.2"
kustomize_version: "3.3.0"
helmfile_version: "0.128.0"
