ubuntu_release: "focal"

# commit to use for local emacs-27 build
emacs27_commit: "de68572742f37f70c128c7192576182347eb8f4b"

go_version: "1.14.6"
go_install_dir: "/opt/go-{{ go_version }}"
go_path: "~/dev/go"
delve_version: "1.5.0"
go_dep_version: "0.5.0"

# Module version to use for the offifical gopls tool (e.g. "HEAD", a branch
# name, a tag name, or a commit hash).
gopls_version: "v0.4.3"

golangci_lint_version: "v1.27.0"

protoc_version: "3.7.1"
protoc_install_dir: "/opt/protoc-{{ protoc_version }}"

nodejs_repo_version: "node_12.x"

clangd_version: "10.0.0"
ccls_version: "0.20190823.5"

dotnet_sdk_version: "3.1"
python_language_server_version: "0.2"

# terraform
tf_version: "0.12.19"
tf_install_dir: "/opt/tf-{{ tf_version }}"
# language server version
tf_ls_version: "v0.0.11-beta2"


# Packer
packer_version: "1.5.1"

eclipse_version: "2019-12"
eclipse_install_dir: "/opt/eclipse-{{ eclipse_version }}"

#
# Kubernetes
#
kubectl_version: "1.16.3"
helm_version: "2.16.1"
helm_install_dir: "/opt/helm-{{ helm_version }}"
minikube_version: "1.5.2"
# kind: kubernetes-in-docker
kind_version: "0.7.0"
clusterawsadm_version: "0.4.2"
kustomize_version: "3.3.0"
