ubuntu_release: "bionic"

go_version: "1.11.2"
go_install_dir: "/opt/go-{{ go_version }}"
go_path: "~/dev/go"
go_dep_version: "0.5.0"

nodejs_repo_version: "node_8.x"

ccls_version: "0.20190301"

# terraform
tf_version: "0.11.10"
tf_install_dir: "/opt/tf-{{ tf_version }}"

kubectl_version: "1.13.0"
helm_version: "2.12.1"
helm_install_dir: "/opt/helm-{{ helm_version }}"
