ubuntu_release: "bionic"

# commit to use for local emacs-27 build
emacs27_commit: "1d10885763287f03a5fb348ba27715e049bb48f8"

go_version: "1.13.4"
go_install_dir: "/opt/go-{{ go_version }}"
go_path: "~/dev/go"
go_dep_version: "0.5.0"

# Module version to use for the offifical gopls tool (e.g. "HEAD", a branch
# name, a tag name, or a commit hash).
gopls_version: "9b52d559c6099a25c1e7b2b4b3d14a51a3463215"

protoc_version: "3.7.1"
protoc_install_dir: "/opt/protoc-{{ protoc_version }}"

nodejs_repo_version: "node_8.x"

ccls_version: "0.20190823.5"

python_language_server_version: "2019.1"

# terraform
tf_version: "0.12.19"
tf_install_dir: "/opt/tf-{{ tf_version }}"

# Packer
packer_version: "1.5.1"

eclipse_version: "2019-12"
eclipse_install_dir: "/opt/eclipse-{{ eclipse_version }}"

#
# Kubernetes
#
kubectl_version: "1.16.3"
helm_version: "2.16.1"
helm_install_dir: "/opt/helm-{{ helm_version }}"
minikube_version: "1.5.2"
# kind: kubernetes-in-docker
kind_version: "0.7.0"
clusterawsadm_version: "0.4.2"
kustomize_version: "3.3.0"
