ubuntu_release: "bionic"

go_version: "1.12"
go_install_dir: "/opt/go-{{ go_version }}"
go_path: "~/dev/go"
go_dep_version: "0.5.0"

# Repo version to checkout for saibing's gopls fork (e.g. "HEAD", a branch
# name, a tag name, or a commit hash).
gopls_saibing_version: "f60b6e7d"

protoc_version: "3.7.1"
protoc_install_dir: "/opt/protoc-{{ protoc_version }}"

nodejs_repo_version: "node_8.x"

ccls_version: "0.20190301"

python_language_server_version: "2019.1"

# terraform
tf_version: "0.11.10"
tf_install_dir: "/opt/tf-{{ tf_version }}"

kubectl_version: "1.13.0"
helm_version: "2.13.1"
helm_install_dir: "/opt/helm-{{ helm_version }}"
