- name: "gocryptfs: install {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
    # allow directory-level encryption
    - gocryptfs
    - libpam-mount # needed to support mounting of encrypted gocrypt filesystem on login
  tags:
  - fs-encryption
  - gocryptfs

# `gocryptfs` is a stacked file-system that allows mounting of encrypted
# folders. Useful for encrypting designated user folders. Example use:
#
#    mkdir dir.enc dir
#    # enter secret password and ALSO TAKE NOTE of the "emergency master key"
#    gocryptfs -init dir.enc/
#
#    # mount at ./dir (you will be prompted for secret password)
#    gocryptfs dir.enc/ dir
#
#    # the encrypted directory can stay mounted for the user session, or be
#    # unmounted manually.
#    fusermount -u dir
#
- name: "gocryptfs: filesystem encryption tool: {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
    # allow directory-level encryption
    - gocryptfs
    # needed to support mounting of encrypted gocrypt filesystem on login
    # see https://github.com/rfjakob/gocryptfs/wiki/Mounting-on-login-using-pam_mount
    - libpam-mount
  tags:
  - fs-encryption
  - gocryptfs


# fscrypt: a high-level tool for managing linux filesystem encryption (the
# kernel part is sometimes also referred to as `fscrypt`)
#
# `fscrypt` is built from source since the current apt package version (`0.2.5`)
# doesn't support v2 encryption policy (fixes some ssh-related issues) out of
# the box.
#
# NOTE: if you later decide to switch to using the Ubuntu package for fscrypt,
# you'll have to first manually run `sudo make uninstall PREFIX=/usr`.
- name: "fscrypt: prerequisites: {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
    - libpam0g-dev
  tags:
  - fs-encryption
  - fscrypt

- name: "fscrypt: git clone"
  become: yes
  git:
    repo:    https://github.com/google/fscrypt.git
    dest:    "{{ fscrypt_repo_dir }}"
    version: "{{ fscrypt_version }}"
    clone: yes
    update: yes
  tags:
  - fs-encryption
  - fscrypt

# installs fscrypt into /usr/bin, pam_fscrypt.so into /usr/lib/security, and
# pam_fscrypt/config into /usr/share/pam-configs
- name: "fscrypt: make install PREFIX=/usr"
  become: yes
  make:
    chdir: "{{ fscrypt_repo_dir }}"
    target: install
    params:
      # note: Ubuntu only recognizes PAM configuration files in /usr, not in
      # /usr/local
      PREFIX=/usr
  environment:
    # need go executable on PATH
    PATH: "/opt/bin:{{ lookup('env', 'PATH') }}"
  tags:
  - fs-encryption
  - fscrypt

# To support the login password protector, we need to apply the fscrypt pam
# (Pluggable Authentication Modules) settings in /usr/share/pam-configs/fscrypt
- name: "fscrypt: enable password-protection via pam module"
  become: yes
  command:
    cmd: /usr/sbin/pam-auth-update --enable fscrypt
  tags:
  - fs-encryption
  - fscrypt


# Some Linux distros use restrictive settings in /etc/pam.d/other that prevent
# programs from checking your login passphrase unless a per-program PAM
# configuration file grants access. This prevents fscrypt from creating any
# login passphrase-protected directories, even without auto-unlocking.
- name: "fscrypt: allow fscrypt to check login passphrase"
  become: yes
  copy:
    src:  files/etc_pam.d_fscrypt
    dest: /etc/pam.d/fscrypt
    mode: 0644
  tags:
  - fs-encryption
  - fscrypt
