- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  roles:
    - repos
    - base
    - fonts
    - emacs
    - firewall
    - desktop
    - dev
    - backup
    - fscrypt
    - email

- hosts: laptop
  gather_facts: no
  become: yes
  become_method: sudo
  roles:
    - laptop
