- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  roles:
    - base
    - firewall
    - desktop
    - dev
    - backup
    - fscrypt
    - mail

- hosts: laptop
  gather_facts: no
  become: yes
  become_method: sudo
  roles:
  - laptop
