- name: "install package management tools: {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
      - apt-transport-https
      - software-properties-common
      - aptitude
      - debconf-utils
      - curl
      - dirmngr
      - snapd
      - debtree
  tags:
    - Base
    - apt
    - repos
    - package-management

- name: "apt repo: canonical partner"
  apt_repository:
    repo: "deb http://archive.canonical.com/ubuntu {{ ubuntu_release }} partner"
    state: present
    update_cache: no
  tags:
    - Base
    - apt
    - repos
    - canonical-partner

- name: "apt repo: canonical partner src"
  apt_repository:
    filename: "canonical-partner"
    repo: "deb-src http://archive.canonical.com/ubuntu {{ ubuntu_release }} partner"
    state: present
    update_cache: no
  tags:
    - Base
    - apt
    - repos
    - canonical-partner

#
# chrome
#
- name: "apt key: google chrome"
  apt_key:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    state: present
  tags:
    - Base
    - apt
    - repos
    - chrome

- name: "apt repo: google chrome"
  apt_repository:
    filename: "google-chrome"
    repo: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    update_cache: no
  tags:
    - Base
    - apt
    - repos
    - chrome

#
# Docker
#
- name: "apt key: docker"
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    keyring: "/etc/apt/trusted.gpg.d/docker.gpg"
    state: present
  tags:
    - Base
    - apt
    - repos
    - docker

- name: "apt repo: docker"
  apt_repository:
    filename: "docker"
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable"
    state: present
    update_cache: no
  tags:
    - Base
    - apt
    - repos
    - docker

#
# vscode
#

- name: "apt key: vscode"
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present
  tags:
    - Base
    - apt
    - repos
    - vscode

- name: "apt repo: vscode"
  apt_repository:
    filename: "vscode"
    repo: "deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main"
    state: present
    update_cache: no
  tags:
    - Base
    - apt
    - repos
    - vscode

#
# gcloud
#

- name: "apt key: gcloud"
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg
    state: present
  tags:
    - Base
    - apt
    - repos
    - gcloud

- name: "apt repo: gcloud"
  apt_repository:
    filename: "gcloud"
    repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main"
    state: present
    update_cache: no
  tags:
    - Base
    - apt
    - repos
    - gcloud

- name: "apt: update cache"
  apt:
    update_cache: yes
  tags:
    - Base
    - apt
    - repos
    - apt-update
