- name: "install package management tools: {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
      - apt-transport-https
      - software-properties-common
      - aptitude
      - debconf-utils
      - curl
      - dirmngr
      - snapd
      - debtree
  tags:
    - Base
    - apt
    - repos
    - package-management

#
# chrome
#
- name: "apt repo: google chrome"
  deb822_repository:
    name: "google-chrome"
    signed_by: "https://dl.google.com/linux/linux_signing_key.pub"
    uris: "https://dl.google.com/linux/chrome/deb/"
    architectures: "amd64"
    suites: stable
    components:
      - main
  tags:
    - Base
    - apt
    - repos
    - chrome

#
# Docker
#
- name: "apt repo: docker"
  deb822_repository:
    name: "docker"
    signed_by: "https://download.docker.com/linux/ubuntu/gpg"
    uris: "https://download.docker.com/linux/ubuntu"
    architectures: "amd64"
    suites: "{{ ubuntu_release }}"
    components:
      - stable
  tags:
    - Base
    - apt
    - repos
    - docker

#
# vscode
#

- name: "apt repo: vscode"
  deb822_repository:
    name: "vscode"
    signed_by: "https://packages.microsoft.com/keys/microsoft.asc"
    uris: "http://packages.microsoft.com/repos/vscode"
    architectures: "amd64"
    suites: stable
    components:
      - main
  tags:
    - Base
    - apt
    - repos
    - vscode

#
# gcloud
#

- name: "apt repo: gcloud"
  deb822_repository:
    name: "gcloud"
    signed_by: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    uris: "http://packages.cloud.google.com/apt"
    architectures: "amd64"
    suites: cloud-sdk
    components:
      - main
  tags:
    - Base
    - apt
    - repos
    - gcloud

#
# Hashicorp (contains vagrant, for instance).
#
- name: "apt repo: hashicorp"
  deb822_repository:
    name: "hashicorp"
    signed_by: "https://apt.releases.hashicorp.com/gpg"
    uris: "https://apt.releases.hashicorp.com"
    architectures: "amd64"
    suites: "{{ ubuntu_release }}"
    components:
      - main
  tags:
    - Base
    - apt
    - repos
    - hashicorp
    - vagrant

# PostgreSQL database

- name: "apt repo: postgresql"
  deb822_repository:
    name: "postgresql"
    signed_by: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    uris: "https://apt.postgresql.org/pub/repos/apt"
    architectures: "amd64"
    suites: "{{ ubuntu_release }}-pgdg"
    components:
      - main
  tags:
    - Base
    - apt
    - repos
    - postgres

# ClickHouse database

- name: "apt repo: clickhouse"
  deb822_repository:
    name: "clickhouse"
    signed_by: "https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key"
    uris: "https://packages.clickhouse.com/deb"
    architectures: "amd64"
    suites: "stable"
    components:
      - main
  tags:
    - Base
    - apt
    - repos
    - clickhouse

#
# Virtualbox
#
- name: "apt repo: virtualbox"
  deb822_repository:
    name: "virtualbox"
    signed_by: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    uris: "https://download.virtualbox.org/virtualbox/debian"
    architectures: "amd64"
    suites: "{{ ubuntu_release }}"
    components:
      - contrib
  tags:
    - Base
    - apt
    - repos
    - vm
    - virtualbox

#
# Mattermost (chat client)
#
- name: "apt repo: mattermost"
  deb822_repository:
    name: "mattermost"
    signed_by: "https://deb.packages.mattermost.com/pubkey.gpg"
    uris: "https://deb.packages.mattermost.com"
    architectures: "amd64"
    suites: "stable"
    components:
      - main
  tags:
    - Base
    - apt
    - repos
    - Desktop
    - internet
    - mattermost

- name: "apt: update cache"
  apt:
    update_cache: yes
  tags:
    - Base
    - apt
    - repos
    - apt-update
