- name: "git: checkout ~/dotfiles"
  become: no # not as root
  git:
    repo: "https://github.com/petergardfjall/dotfiles.git"
    recursive: yes
    dest: "{{ '~/dotfiles' | expanduser }}"
    clone: yes
    update: no
  tags:
    - Base
    - dotfiles

- name: "git: set ssh remote for ~/dotfiles"
  become: no
  git_config:
    name: remote.origin.url
    value: git@github.com:petergardfjall/dotfiles.git
    scope: local
    repo: "{{ '~/dotfiles' | expanduser }}"
  tags:
    - Base
    - dotfiles

- name: "git: update ~/.gitconfig"
  become: no # not as root
  shell: "~/dotfiles/setup-git-config.sh"
  changed_when: False # don't appear changed
  tags:
    - Base
    - dotfiles
    - gitconfig

- name: ".bashrc: extra modules"
  become: no # not as root
  blockinfile:
    path: "{{ '~/.bashrc' | expanduser }}"
    block: |
      #
      # source additional configuration modules
      #
      source ~/dotfiles/bash.includes
  tags:
    - Base
    - dotfiles
    - bash

- name: ".profile: extra modules"
  become: no # not as root
  blockinfile:
    path: "{{ '~/.profile' | expanduser }}"
    block: |
      #
      # source additional configuration modules
      #
      source ~/dotfiles/bash.includes
  tags:
    - Base
    - dotfiles
    - bash

- name: "~/inputrc: emacs-like copy/paste in terminal"
  become: no
  copy:
    src: files/inputrc
    dest: "{{ '~/.inputrc' | expanduser }}"
    mode: 0644
  tags:
    - Base
    - dotfiles
    - inputrc

- name: "vscode: create config dir"
  become: no # not as root
  file:
    path: "{{ '~/.config/Code/User' | expanduser }}"
    state: directory
  tags:
    - Base
    - dotfiles
    - vscode

- name: "vscode: symlink for settings.json"
  become: no # not as root
  file:
    src: "{{ '~/dotfiles/vscode/settings.json' | expanduser }}"
    dest: "{{ '~/.config/Code/User/settings.json' | expanduser }}"
    state: link
  tags:
    - Base
    - dotfiles
    - vscode

- name: "vscode: symlink for keybindings.json"
  become: no # not as root
  file:
    src: "{{ '~/dotfiles/vscode/keybindings.json' | expanduser }}"
    dest: "{{ '~/.config/Code/User/keybindings.json' | expanduser }}"
    state: link
  tags:
    - Base
    - dotfiles
    - vscode

- name: "prettier: symlink for .prettierrc.yaml"
  become: no # not as root
  file:
    src: "{{ '~/dotfiles/.prettierrc.yaml' | expanduser }}"
    dest: "{{ '~/.prettierrc.yaml' | expanduser }}"
    state: link
  tags:
    - Base
    - dotfiles
    - prettier
