- name: "miniconda: check current version"
  become: no
  shell: ~/miniconda3/bin/conda --version
  register: miniconda_v
  ignore_errors: yes
  changed_when: False # read-only: won't change machine state
  tags:
    - Dev
    - machine-learning
    - miniconda

- name: "miniconda: download installer"
  become: "no" # not as root
  get_url:
    url: "https://repo.anaconda.com/miniconda/Miniconda3-{{ miniconda_py_version }}_{{ miniconda_version }}-0-Linux-x86_64.sh"
    checksum: "{{ miniconda_checksum }}"
    dest: "/tmp/Miniconda.sh"
  when: (miniconda_v is failed) or (not miniconda_version in miniconda_v.stdout)
  tags:
    - Dev
    - machine-learning
    - miniconda

# installs conda under `~/miniconda3`.
#
# To complete the installation, add an alias:
#   alias conda-activate='source <(~/miniconda3/bin/conda shell.bash hook)'
#
#   conda env list
#   conda create --name my-env python=3.8 -y
#   conda activate my-env
#
- name: "miniconda: install"
  become: "no" # not as root
  shell: "/bin/bash /tmp/Miniconda.sh -b -u -f"
  when: (miniconda_v is failed) or (not miniconda_version in miniconda_v.stdout)
  tags:
    - Dev
    - machine-learning
    - miniconda
