#
# Rclone
#
- name: "rclone: install"
  apt:
    name: "rclone"
    state: latest
    install_recommends: yes
  tags:
    - Security
    - backup
    - rclone

#
# Duplicity
#
- name: "duplicity: install"
  apt:
    name: duplicity
    state: latest
    install_recommends: yes
  tags:
    - Security
    - backup
    - duplicity
