- name: "duplicity: install"
  snap:
    name:
    - duplicity
    channel: "stable"
    classic: "yes"
  tags:
  - backup
  - duplicity

- name: "rclone: install"
  apt:
    name: "rclone"
    state: latest
    install_recommends: yes
  tags:
  - backup
  - rclone
