- name: "duplicity: install prerequisites: {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
    - librsync-dev
  tags:
  - backup
  - duplicity

- name: "duplicity: install"
  become: yes # want to be able to backup privileged directories
  pip:
    name:
    - duplicity>0.8
    - PyDrive>1.3
    - boto3>1.12
  tags:
  - backup
  - duplicity

- name: "rclone: install"
  apt:
    name: "rclone"
    state: latest
    install_recommends: yes
  tags:
  - backup
  - rclone
