- name: "duplicity: install"
  snap:
    name:
    - duplicity
    channel: "stable"
    classic: "yes"
  tags:
  - backup
  - duplicity

# needed to allow cron job to run duplicity
- name: "duplicity: symlink under /usr/bin"
  file:
    src:  "/snap/bin/duplicity"
    dest: "/usr/bin/duplicity"
    state: link
  tags:
  - backup
  - duplicity

- name: "rclone: install"
  apt:
    name: "rclone"
    state: latest
    install_recommends: yes
  tags:
  - backup
  - rclone
