- name: "install {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
      - laptop-mode-tools
  tags:
    - Laptop
    - laptop
    - laptop-mode-tools
