- name: "google chrome: install"
  apt:
    name: google-chrome-stable
    state: latest
    install_recommends: yes
  tags:
    - Desktop
    - internet
    - chrome

- name: "skype: install"
  snap:
    name:
      - skype
    channel: "stable"
    classic: "yes"
  tags:
    - Desktop
    - internet
    - skype

- name: "slack: install"
  snap:
    name:
      - slack
    channel: "stable"
    classic: "yes"
  tags:
    - Desktop
    - internet
    - slack
