- name: "ufw: deny all and enable"
  ufw:
    state: enabled
    direction: incoming
    policy: deny
  tags:
    - Security
    - firewall
    - ufw

- name: "ufw: allow ssh access (port 22)"
  ufw:
    rule: allow
    direction: in
    port: 22
  tags:
    - Security
    - firewall
    - ufw
