# Prettier is an opinionated code-formatter for many languages (JavaScript, JSX,
# yaml). See https://prettier.io/. Used in Emacs.
- name: "prettier: install"
  become: no
  npm:
    name: "{{ item }}"
    # npm install -g <pkg>
    global: yes
  loop:
    - prettier
  tags:
    - Dev
    - dev-tools
    - prettier

- name: "ripgrep: install"
  become: no
  shell: "{{ item }}"
  changed_when: False # don't display as "changed"
  loop:
    - "~/.cargo/bin/cargo install ripgrep --version {{ ripgrep_version }}"
  tags:
    - Dev
    - dev-tools
    - ripgrep

# diffr: refined highlighting of changes in git diffs
- name: "diffr: install"
  become: no
  shell: "{{ item }}"
  changed_when: False # don't display as "changed"
  loop:
    - "~/.cargo/bin/cargo install diffr --version {{ diffr_version }}"
  tags:
    - Dev
    - dev-tools
    - diffr

- name: "yq: install"
  become: no # not as root
  pip:
    executable: pip3
    extra_args: --user # install under ~/.local
    name:
      # jq-like tool for yaml
      - yq
  tags:
    - Dev
    - dev-tools
    - yq

# Generate and parse Universally Unique Lexicographically Sortable Identifiers.
- name: "ulid: install"
  become: no # not as root
  command: "/opt/bin/go install {{ item }}"
  changed_when: False # don't view as changes in end result
  loop:
    - "github.com/oklog/ulid/v2/cmd/ulid@v2.1.0"
  tags:
    - Dev
    - dev-tools
    - ulid

# Command-line tool for interacting with gRPC servers.
- name: "grpcurl: install"
  become: no # not as root
  command: "/opt/bin/go install {{ item }}"
  changed_when: False # don't view as changes in end result
  loop:
    - "github.com/fullstorydev/grpcurl/cmd/grpcurl@{{ grpcurl_version }}"
  tags:
    - Dev
    - dev-tools
    - grpcurl

#
# tinyproxy
#

- name: "tinyproxy: clone git repo"
  git:
    repo: "https://github.com/tinyproxy/tinyproxy"
    recursive: yes
    dest: "/opt/tinyproxy"
    clone: yes
    update: no
    version: "{{ tinyproxy_version }}"
  tags:
    - Dev
    - dev-tools
    - tinyproxy

- name: "tinyproxy: build and install under /usr/local/bin/tinyproxy"
  shell: "./autogen.sh && ./configure --prefix=/usr/local && make && make install"
  args:
    chdir: "/opt/tinyproxy"
  tags:
    - Dev
    - dev-tools
    - tinyproxy

# Command-line tool for signing, verifying, and bundling TLS certificates.
- name: "cfssl: install"
  become: no # not as root
  command: "/opt/bin/go install github.com/cloudflare/cfssl/cmd/...@{{ cfssl_version }}"
  changed_when: False # don't view as changes in end result
  tags:
    - Dev
    - dev-tools
    - cfssl

# HTML language server.
- name: "vscode-html-languageserver: install"
  become: no
  npm:
    name: "{{ item }}"
    # npm install -g <pkg>
    global: yes
  loop:
    - vscode-html-languageserver-bin
  tags:
    - Dev
    - dev-tools
    - vscode-html-languageserver
    - html

# Bash language server.
- name: "bash-language-server: install"
  become: no
  npm:
    name: "{{ item }}"
    # npm install -g <pkg>
    global: yes
  loop:
    - bash-language-server
  tags:
    - Dev
    - dev-tools
    - bash-language-server
    - bash

# Python language server: pylsp.
# See https://github.com/python-lsp/python-lsp-server
- name: "python-lsp-server: install"
  become: no # not as root
  pip:
    executable: pip3
    extra_args: --user # install under ~/.local
    name:
      # Install with all optional providers.
      - python-lsp-server[all]
  tags:
    - Dev
    - dev-tools
    - python-lsp-server
    - python

# Generate data types and converters from JSON, JSON Schema to a multitude of
# languages: Go, Python, Java, etc.
- name: "quicktype: install"
  become: no
  npm:
    name: "{{ item }}"
    # npm install -g <pkg>
    global: yes
  loop:
    - quicktype
  tags:
    - Dev
    - dev-tools
    - quicktype

# GNU Octave is a scientific programming language largely compatible with Matlab.
- name: "octave: install"
  apt:
    name: octave
    state: latest
    install_recommends: yes
  tags:
    - Dev
    - dev-tools
    - octave
    - math
    - matlab
