- name: "create /opt/bin"
  file:
    path: /opt/bin
    state: directory
    mode: 0755

- name: "create /scratch"
  file:
    path: /scratch
    state: directory
    mode: 0777

- name: "apt: update cache"
  apt:
    update_cache: true
  changed_when: False  # don't appear changed

- name: "install package management tools: {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
    - apt-transport-https
    - software-properties-common
    - aptitude
    - debconf-utils
    - curl
    - dirmngr
    - snapd

- name: "apt repo: canonical partner"
  apt_repository:
    repo: "deb http://archive.canonical.com/ubuntu {{ ubuntu_release }} partner"
    state: present

- name: "apt repo: canonical partner src"
  apt_repository:
    repo: "deb-src http://archive.canonical.com/ubuntu {{ ubuntu_release }} partner"
    state: present

- name: "apt: update cache"
  apt:
    update_cache: true
  changed_when: False  # don't appear changed

- name: "install basic tools: {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
    # shell
    - bash-completion
    - tmux
    # shell utilities
    - pwgen
    - tree
    - jq
    - pass
    - dos2unix
    # desktop/X
    - wmctrl
    - xdotool
    - xsel
    # filesystem
    - gparted
    - sshfs
    # monitoring
    - htop
    - iftop
    - bmon
    - iperf
    - sysstat
    - powertop
    # graphics
    - inkscape
    - gimp
    - gpick
    - gnuplot
    # communication
    - openssh-server
    - openssh-client
    - chromium-browser
    # version control
    - git
    - gitg
    - tig
    - subversion
    - meld
    - markdown
    # gpg password entry in text-mode
    - pinentry-tty
    - pinentry-curses
    - dia
    # common build utilities
    - autoconf
    - build-essential


- name: "apt key: emacs26"
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "873503A090750CDAEB0754D93FF0E01EEAAFC9CD"
    state: present
  tags: emacs


- name: "apt repo: emacs26"
  apt_repository:
    filename: emacs26
    repo: "deb http://ppa.launchpad.net/kelleyk/emacs/ubuntu {{ ubuntu_release }} main"
    state: present
  tags: emacs

- name: "apt: update cache"
  apt:
    update_cache: true
  changed_when: False  # don't appear changed

- name: "install: {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
    - emacs26
    # a faster grep for code (used by emacs ag package)
    - silversearcher-ag
    # GNU global source code tagging (gtags) and querying (global)
    - global
    # extends global/gtags with support for C#, Py, Ruby, ...
    # NOTE: for additional lang support (Go, D, Rust, Clojure) we also
    # manually build/install universal-ctags below.
    # NOTE: set GTAGSLABEL=exuberant-ctags to make use of this backend.
    - exuberant-ctags
    # extends global/gtags with support for F#, Haskell, ..
    # NOTE: set GTAGSLABEL=pygments-parser to make use of this backend.
    - python-pygments
  tags: emacs

# universal-ctags extends language support for global/gtags
# NOTE: set GTAGSLABEL=universal-ctags to make use of this backend.
- name: "universal-ctags: clone git repo"
  git:
    repo: 'https://github.com/universal-ctags/ctags'
    recursive: yes
    dest: "/opt/universal-ctags"
    clone: yes
    update: no
  tags: ['emacs', 'ctags', 'gtags', 'global']

- name: "universal-ctags: build and install under /usr/local/bin/ctags"
  shell: "./autogen.sh && ./configure --prefix=/usr/local && make && make install"
  args:
    chdir: "/opt/universal-ctags"
  tags: ['emacs', 'ctags', 'gtags', 'global']

- name: "global: place config under ~/.globalrc "
  become: no
  copy:
    src: files/globalrc
    dest: "{{ '~/.globalrc' | expanduser }}"
    mode: 0644
  tags: ['emacs', 'ctags', 'gtags', 'global']

# pandoc is used by emacs markdown-preview-mode
- name: "install: pandoc"
  apt:
    deb: "https://github.com/jgm/pandoc/releases/download/2.6/pandoc-2.6-1-amd64.deb"
  tags: emacs

- name: "truecolor terminal: create ~/xterm-24bit.terminfo file"
  become: no
  blockinfile:
    path: "{{ '~/xterm-24bit.terminfo' | expanduser }}"
    block: |
      xterm-24bit|xterm with 24-bit direct color mode,
         use=xterm-256color,
         sitm=\E[3m,
         ritm=\E[23m,
         setb24=\E[48;2;%p1%{65536}%/%d;%p1%{256}%/%{255}%&%d;%p1%{255}%&%dm,
         setf24=\E[38;2;%p1%{65536}%/%d;%p1%{256}%/%{255}%&%d;%p1%{255}%&%dm,
    create: yes
  tags: emacs

# this allows us to 'export TERM=xterm-24bit' to make use of truecolor
# terminal
- name: "truecolor terminal: create ~/.terminfo"
  become: no
  shell: "tic -x -o ~/.terminfo ~/xterm-24bit.terminfo"
  args:
    creates: "{{ '~/.terminfo' | expanduser }}"
  tags: emacs

- name: "generate swedish locale"
  shell: locale-gen sv_SE
  changed_when: False  # don't appear changed

- name: "apt: clean unneeded packages"
  apt:
    autoremove: true

- name: "git: checkout dotfiles"
  become: no   # not as root
  git:
    repo: 'https://github.com/petergardfjall/dotfiles.git'
    recursive: yes
    dest: "{{ '~/dotfiles' | expanduser }}"
    clone: yes
    update: no

- name: "emacs: create symlink for ~/.emacs"
  become: no   # not as root
  file:
    src: "{{ '~/dotfiles/emacs-init.el' | expanduser }}"
    dest: "{{ '~/.emacs' | expanduser }}"
    state: link

- name: "vscode: create config dir"
  become: no   # not as root
  file:
    path: "{{ '~/.config/Code/User' | expanduser }}"
    state: directory

- name: "vscode: symlink for settings.json"
  become: no   # not as root
  file:
    src: "{{ '~/dotfiles/vscode/settings.json' | expanduser }}"
    dest: "{{ '~/.config/Code/User/settings.json' | expanduser }}"
    state: link

- name: "vscode: symlink for keybindings.json"
  become: no   # not as root
  file:
    src: "{{ '~/dotfiles/vscode/keybindings.json' | expanduser }}"
    dest: "{{ '~/.config/Code/User/keybindings.json' | expanduser }}"
    state: link

- name: ".bashrc: extra modules"
  become: no   # not as root
  blockinfile:
    path: "{{ '~/.bashrc' | expanduser }}"
    block: |
      #
      # source additional configuration modules
      #
      source ~/dotfiles/bash.includes

- name: ".profile: extra modules"
  become: no   # not as root
  blockinfile:
    path: "{{ '~/.profile' | expanduser }}"
    block: |
      #
      # source additional configuration modules
      #
      source ~/dotfiles/bash.includes

- name: "git: checkout helper scripts"
  become: no   # not as root
  git:
    repo: 'https://github.com/petergardfjall/scripts'
    recursive: yes
    dest: "{{ '~/bin/scripts' | expanduser }}"
    clone: yes
    update: no
