- name: "create /opt/bin"
  file:
    path: /opt/bin
    state: directory
    mode: 0755

- name: "create /scratch"
  file:
    path: /scratch
    state: directory
    mode: 0777

- name: "install package management tools: {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
    - apt-transport-https
    - software-properties-common
    - aptitude
    - debconf-utils
    - curl
    - dirmngr
    - snapd
  tags:
  - apt
  - package-management

- name: "apt repo: canonical partner"
  apt_repository:
    repo: "deb http://archive.canonical.com/ubuntu {{ ubuntu_release }} partner"
    state: present
    update_cache: yes
  tags:
  - apt-repos

- name: "apt repo: canonical partner src"
  apt_repository:
    repo: "deb-src http://archive.canonical.com/ubuntu {{ ubuntu_release }} partner"
    state: present
    update_cache: yes
  tags:
  - apt-repos

- name: "install basic tools: {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
    # shell
    - bash-completion
    - tmux
    # shell utilities
    - pwgen
    - tree
    - jq
    - pass
    - dos2unix
    # desktop/X
    - wmctrl
    - xdotool
    - xsel
    # filesystem
    - gparted
    - sshfs
    # monitoring
    - htop
    - iftop
    - bmon
    - iperf
    - sysstat
    - powertop
    - httperf
    # network
    - nmap
    - tinyproxy # light-weight HTTP/HTTPS proxy daemon
    # graphics
    - inkscape
    - gimp
    - gpick
    - gnuplot
    # communication
    - openssh-server
    - openssh-client
    # version control
    - git
    - gitg
    - tig
    - subversion
    - mercurial
    - meld
    # markdown rendering
    - markdown
    # gpg password entry in text-mode
    - pinentry-tty
    - pinentry-curses
    # diagrams
    - dia
    - graphviz
    # webcam
    - cheese
    # allow directory-level encryption
    - gocryptfs
    - libpam-mount # needed to support mounting of encrypted gocrypt filesystem on login
  tags:
  - basictools

# `gocryptfs` is a stacked file-system that allows mounting of encrypted
# folders. Useful for encrypting designated user folders. Example use:
#
#    mkdir dir.enc dir
#    # enter secret password and ALSO TAKE NOTE of the "emergency master key"
#    gocryptfs -init dir.enc/
#
#    # mount at ./dir (you will be prompted for secret password)
#    gocryptfs dir.enc/ dir
#
#    # the encrypted directory can stay mounted for the user session, or be
#    # unmounted manually.
#    fusermount -u dir
#
- name: "gocryptfs: filesystem encryption tool: {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
    # allow directory-level encryption
    - gocryptfs
    # needed to support mounting of encrypted gocrypt filesystem on login
    # see https://github.com/rfjakob/gocryptfs/wiki/Mounting-on-login-using-pam_mount
    - libpam-mount
  tags:
  - fs-encryption
  - gocryptfs

# fscrypt: a high-level tool for managing linux filesystem encryption (the
# kernel part is sometimes also referred to as `fscrypt`)
#
# `fscrypt` is built from source since the current apt package version (`0.2.5`)
# doesn't support v2 encryption policy (fixes some ssh-related issues) out of
# the box.
#
# NOTE: if you later decide to switch to using the Ubuntu package for fscrypt,
# you'll have to first manually run `sudo make uninstall PREFIX=/usr`.
- name: "fscrypt: prerequisites: {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
    - libpam0g-dev
  tags:
  - fs-encryption
  - fscrypt

- name: "fscrypt: git clone"
  become: yes
  git:
    repo:    https://github.com/google/fscrypt.git
    dest:    "{{ fscrypt_repo_dir }}"
    version: "{{ fscrypt_version }}"
    clone: yes
    update: no
  tags:
  - fs-encryption
  - fscrypt

# installs fscrypt into /usr/bin, pam_fscrypt.so into /usr/lib/security, and
# pam_fscrypt/config into /usr/share/pam-configs
- name: "fscrypt: make install PREFIX=/usr"
  become: yes
  make:
    chdir: "{{ fscrypt_repo_dir }}"
    target: install
    params:
      # note: Ubuntu only recognizes PAM configuration files in /usr, not in
      # /usr/local
      PREFIX=/usr
  environment:
    # need go executable on PATH
    PATH: "/opt/bin:{{ lookup('env', 'PATH') }}"
  tags:
  - fs-encryption
  - fscrypt



- name: "build tools: {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    # build tools that may be needed to build other base tools from source
    packages:
    - make
    - pkg-config
    - autoconf
    - automake
    - build-essential
    - gcc
    - gettext
  tags:
  - buildtools


- name: "~/inputrc: emacs copy/paste in terminal"
  become: no
  copy:
    src: files/inputrc
    dest: "{{ '~/.inputrc' | expanduser }}"
    mode: 0644
  tags:
  - terminal


#
# chrome
#
- name: "apt key: google chrome"
  apt_key:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    state: present
  tags:
  - apt-repos
  - chrome

- name: "apt repo: google chrome"
  apt_repository:
    filename: "google-chrome"
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    update_cache: yes
  tags:
  - apt-repos
  - chrome

- name: "google chrome: install"
  apt:
    name: google-chrome-stable
    state: latest
    install_recommends: yes
  tags:
  - chrome


#
# Emacs
#

- name: "emacs: prerequisites: {{ packages }}"
  vars:
    packages:
    # see https://www.emacswiki.org/emacs/EmacsSnapshotAndDebian
    - texinfo
    - xorg-dev
    - libgtk-3-dev
    - libxpm-dev
    - libjpeg-dev
    - libgif-dev
    - libtiff5-dev
    - libm17n-dev
    - libpng-dev
    - librsvg2-dev
    - libotf-dev
    - libgnutls28-dev
    - libncurses5-dev
    - libjansson-dev
    - libharfbuzz-dev
    - libharfbuzz-bin
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  tags:
  - emacs

- name: "emacs: build tag/commit: {{ emacs_rev }}"
  shell: |
    {{ role_path}}/scripts/build-emacs.sh {{ emacs_rev | quote }}
  args:
    creates: "/opt/emacs-src/.BUILT_{{ emacs_rev }}"
  tags:
  - emacs

- name: "emacs: /usr/local/bin/emacs symlink"
  file:
    src:  /opt/emacs-src/src/emacs
    dest: /usr/local/bin/emacs
    force: yes
    state: link
  tags:
  - emacs

- name: "install: {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
    # a faster grep for code (used by emacs ag package)
    - silversearcher-ag
    # GNU global source code tagging (gtags) and querying (global)
    - global
    # extends global/gtags with support for C#, Py, Ruby, ...
    # NOTE: for additional lang support (Go, D, Rust, Clojure) we also
    # manually build/install universal-ctags below.
    # NOTE: set GTAGSLABEL=exuberant-ctags to make use of this backend.
    - exuberant-ctags
    # extends global/gtags with support for F#, Haskell, ..
    # NOTE: set GTAGSLABEL=pygments-parser to make use of this backend.
    - python3-pygments
  tags:
  - emacs
  - global

- name: "universal-ctags: install prerequisites: {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
    - python3-docutils
    - libseccomp-dev
    - libjansson-dev
    - libyaml-dev
    - libxml2-dev
  tags:
  - emacs
  - global

- name: "emacs vterm: install {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
    - libtool-bin
    - libvterm-dev
  tags:
  - emacs
  - vterm


# universal-ctags extends language support for global/gtags
# NOTE: set GTAGSLABEL=universal-ctags to make use of this backend.
- name: "universal-ctags: clone git repo"
  git:
    repo: 'https://github.com/universal-ctags/ctags'
    recursive: yes
    dest: "/opt/universal-ctags"
    clone: yes
    update: no
  tags: ['emacs', 'ctags', 'gtags', 'global']

- name: "universal-ctags: build and install under /usr/local/bin/ctags"
  shell: "./autogen.sh && ./configure --prefix=/usr/local && make && make install"
  args:
    chdir: "/opt/universal-ctags"
  tags: ['emacs', 'ctags', 'gtags', 'global']

- name: "global: place config under ~/.globalrc "
  become: no
  copy:
    src: files/globalrc
    dest: "{{ '~/.globalrc' | expanduser }}"
    mode: 0644
  tags: ['emacs', 'ctags', 'gtags', 'global']

# pandoc is used by emacs markdown-preview-mode
- name: "install: pandoc"
  apt:
    deb: "https://github.com/jgm/pandoc/releases/download/2.6/pandoc-2.6-1-amd64.deb"
  tags: emacs

- name: "truecolor terminal: create ~/xterm-24bit.terminfo file"
  become: no
  blockinfile:
    path: "{{ '~/xterm-24bit.terminfo' | expanduser }}"
    block: |
      xterm-24bit|xterm with 24-bit direct color mode,
         use=xterm-256color,
         sitm=\E[3m,
         ritm=\E[23m,
         setb24=\E[48;2;%p1%{65536}%/%d;%p1%{256}%/%{255}%&%d;%p1%{255}%&%dm,
         setf24=\E[38;2;%p1%{65536}%/%d;%p1%{256}%/%{255}%&%d;%p1%{255}%&%dm,
    create: yes
  tags: emacs

# this allows us to 'export TERM=xterm-24bit' to make use of truecolor
# terminal
- name: "truecolor terminal: create ~/.terminfo"
  become: no
  shell: "tic -x -o ~/.terminfo ~/xterm-24bit.terminfo"
  args:
    creates: "{{ '~/.terminfo' | expanduser }}"
  tags: emacs



- name: "generate swedish locale"
  shell: locale-gen sv_SE
  changed_when: False  # don't appear changed

- name: "apt: clean unneeded packages"
  apt:
    autoremove: true

#
# dot files
#

- name: "git: checkout ~/dotfiles"
  become: no   # not as root
  git:
    repo: 'https://github.com/petergardfjall/dotfiles.git'
    recursive: yes
    dest: "{{ '~/dotfiles' | expanduser }}"
    clone: yes
    update: no
  tags:
  - dotfiles

- name: "git: set ssh remote for ~/dotfiles"
  become: no
  git_config:
    name:  remote.origin.url
    value: git@github.com:petergardfjall/dotfiles.git
    scope: local
    repo:  "{{ '~/dotfiles' | expanduser }}"
  tags:
  - dotfiles

- name: "git: checkout ~/.emacs.d/"
  become: no   # not as root
  git:
    repo: 'https://github.com/petergardfjall/.emacs.d.git'
    recursive: yes
    dest: "{{ '~/.emacs.d' | expanduser }}"
    clone: yes
    update: no
  tags:
  - dotfiles
  - emacs

- name: "git: set ssh remote for ~/.emacs.d"
  become: no
  git_config:
    name:  remote.origin.url
    value: git@github.com:petergardfjall/.emacs.d.git
    scope: local
    repo:  "{{ '~/.emacs.d' | expanduser }}"
  tags:
  - dotfiles
  - emacs

- name: "vscode: create config dir"
  become: no   # not as root
  file:
    path: "{{ '~/.config/Code/User' | expanduser }}"
    state: directory
  tags:
  - dotfiles

- name: "vscode: symlink for settings.json"
  become: no   # not as root
  file:
    src: "{{ '~/dotfiles/vscode/settings.json' | expanduser }}"
    dest: "{{ '~/.config/Code/User/settings.json' | expanduser }}"
    state: link
  tags:
  - dotfiles

- name: "vscode: symlink for keybindings.json"
  become: no   # not as root
  file:
    src: "{{ '~/dotfiles/vscode/keybindings.json' | expanduser }}"
    dest: "{{ '~/.config/Code/User/keybindings.json' | expanduser }}"
    state: link
  tags:
  - dotfiles

- name: ".bashrc: extra modules"
  become: no   # not as root
  blockinfile:
    path: "{{ '~/.bashrc' | expanduser }}"
    block: |
      #
      # source additional configuration modules
      #
      source ~/dotfiles/bash.includes
  tags:
  - dotfiles

- name: ".profile: extra modules"
  become: no   # not as root
  blockinfile:
    path: "{{ '~/.profile' | expanduser }}"
    block: |
      #
      # source additional configuration modules
      #
      source ~/dotfiles/bash.includes
  tags:
  - dotfiles

- name: "git: checkout ~/bin/scripts"
  become: no   # not as root
  git:
    repo: 'https://github.com/petergardfjall/scripts'
    recursive: yes
    dest: "{{ '~/bin/scripts' | expanduser }}"
    clone: yes
    update: no
  tags:
  - dotfiles

- name: "git: set ssh remote for ~/bin/scripts"
  become: no
  git_config:
    name:  remote.origin.url
    value: git@github.com:petergardfjall/scripts.git
    scope: local
    repo:  "{{ '~/bin/scripts' | expanduser }}"
  tags:
  - dotfiles
