- name: "create /opt/bin"
  file:
    path: /opt/bin
    state: directory
    mode: 0755

- name: "create /scratch"
  file:
    path: /scratch
    state: directory
    mode: 0777

- name: "apt: update cache"
  apt:
    update_cache: true
  changed_when: False  # don't appear changed

- name: "install package management tools: {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
    - apt-transport-https
    - software-properties-common
    - aptitude
    - debconf-utils
    - curl
    - dirmngr
    - snapd

- name: "apt repo: canonical partner"
  apt_repository:
    repo: "deb http://archive.canonical.com/ubuntu {{ ubuntu_release }} partner"
    state: present

- name: "apt repo: canonical partner src"
  apt_repository:
    repo: "deb-src http://archive.canonical.com/ubuntu {{ ubuntu_release }} partner"
    state: present

- name: "apt: update cache"
  apt:
    update_cache: true
  changed_when: False  # don't appear changed

- name: "install basic tools: {{ packages }}"
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: yes
  vars:
    packages:
    # shell
    - bash-completion
    - tmux
    # shell utilities
    - pwgen
    - tree
    - jq
    - pass
    - dos2unix
    # desktop/X
    - wmctrl
    - xdotool
    - xsel
    # filesystem
    - gparted
    - sshfs
    # monitoring
    - htop
    - iftop
    - bmon
    - iperf
    - sysstat
    - powertop
    # graphics
    - inkscape
    - gimp
    - gpick
    - gnuplot
    # communication
    - openssh-server
    - openssh-client
    - chromium-browser
    # version control
    - git
    - gitg
    - tig
    - subversion
    - meld
    # code/editing
    - silversearcher-ag
    - global
    - emacs25
    - markdown

- name: "generate swedish locale"
  shell: locale-gen sv_SE
  changed_when: False  # don't appear changed

- name: "apt: clean unneeded packages"
  apt:
    autoremove: true

- name: "git: checkout dotfiles"
  become: no   # not as root
  git:
    repo: 'https://github.com/petergardfjall/dotfiles.git'
    recursive: yes
    dest: "{{ '~/dotfiles' | expanduser }}"
    clone: yes
    update: no

- name: "emacs: create symlink for ~/.emacs"
  become: no   # not as root
  file:
    src: "{{ '~/dotfiles/emacs-init.el' | expanduser }}"
    dest: "{{ '~/.emacs' | expanduser }}"
    state: link

- name: "vscode: create config dir"
  become: no   # not as root
  file:
    path: "{{ '~/.config/Code/User' | expanduser }}"
    state: directory

- name: "vscode: symlink for settings.json"
  become: no   # not as root
  file:
    src: "{{ '~/dotfiles/vscode/settings.json' | expanduser }}"
    dest: "{{ '~/.config/Code/User/settings.json' | expanduser }}"
    state: link

- name: "vscode: symlink for keybindings.json"
  become: no   # not as root
  file:
    src: "{{ '~/dotfiles/vscode/keybindings.json' | expanduser }}"
    dest: "{{ '~/.config/Code/User/keybindings.json' | expanduser }}"
    state: link

- name: ".bashrc: extra modules"
  become: no   # not as root
  blockinfile:
    path: "{{ '~/.bashrc' | expanduser }}"
    block: |
      #
      # source additional configuration modules
      #
      source ~/dotfiles/bash.includes

- name: ".profile: extra modules"
  become: no   # not as root
  blockinfile:
    path: "{{ '~/.profile' | expanduser }}"
    block: |
      #
      # source additional configuration modules
      #
      source ~/dotfiles/bash.includes

- name: "git: checkout helper scripts"
  become: no   # not as root
  git:
    repo: 'https://github.com/petergardfjall/scripts'
    recursive: yes
    dest: "{{ '~/bin/scripts' | expanduser }}"
    clone: yes
    update: no
